name: Deploy React Web

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [subrepo-updated]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      # 🧩 Chuẩn bị thư mục build trên VPS
      - name: Prepare VPS folder
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ vars.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ vars.VPS_PORT }}
          script: |
            mkdir -p /home/${{ vars.VPS_USER }}/apps/${{ vars.PROJECT_NAME }}/build
            rm -rf /home/${{ vars.VPS_USER }}/apps/${{ vars.PROJECT_NAME }}/build/*

      # 🧠 Upload đúng nội dung (fix lỗi build/build)
      - name: Upload build to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ vars.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ vars.VPS_PORT }}
          source: "build/*"
          target: "/home/${{ vars.VPS_USER }}/apps/${{ vars.PROJECT_NAME }}/build"

      # 🔁 Restart PM2 và serve đúng thư mục build
      - name: Restart PM2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ vars.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ vars.VPS_PORT }}
          script: |
            cd /home/${{ vars.VPS_USER }}/apps/${{ vars.PROJECT_NAME }}
            pm2 stop ${{ vars.PROJECT_NAME }} || true
            pm2 delete ${{ vars.PROJECT_NAME }} || true
            # ✅ Dùng đường dẫn tuyệt đối để tránh lỗi serve sai thư mục
            pm2 start "npx serve -s /home/${{ vars.VPS_USER }}/apps/${{ vars.PROJECT_NAME }}/build -l ${{ vars.PROJECT_PORT }} --no-clipboard" --name ${{ vars.PROJECT_NAME }}
            pm2 save
